version: '2'

services:
  vpn:
    image: dperson/openvpn-client
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
#    dns: 172.31.0.71
#    dns_search: dasie.mimuw.edu.pl
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
    # launch using the command line arguments, IE pick one:
      - ./vpn:/vpn
    # command: 'server;user;password[;port]'

  # Replace "service1" with and image with an actual service you want to run
  worker:
    build: ./worker
    depends_on:
      - vpn
    environment:
      TZ: 'EST5EDT'
      FILETRACKER_URL: 'http://db0:39999/'
      SIOWORKERSD_HOST: 'glados'
    network_mode: "service:vpn"
    restart: unless-stopped
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    volumes:
      - /srv/service1:/var/lib/service1:Z

networks:
  default:
